---
- name: Install Zabbix server
  hosts: test_server
  become: yes
  become_method: sudo
  vars:
   db_name: "zabbix"
   db_user: "zabbix"
   db_password: "devops"
   page_name: "192.168.20.133"
   listen_name: "80"

  tasks:
    - name: Update apt packages
      apt:
        update_cache: yes

    - name: Install a .deb package zabbix
      apt:
        deb: https://repo.zabbix.com/zabbix/7.0/ubuntu/pool/main/z/zabbix-release/zabbix-release_latest_7.0+ubuntu22.04_all.deb

    - name: Install zabbix server, frontend
      apt:
        name:
        - zabbix-server-pgsql
        - zabbix-frontend-php
        - php8.1-pgsql
        - zabbix-nginx-conf
        - zabbix-sql-scripts
        - zabbix-agent2
        state: present

    - name: Install Zabbix agent2 plugins
      apt:
        name:
        - zabbix-agent2-plugin-mongodb
        - zabbix-agent2-plugin-mssql
        - zabbix-agent2-plugin-postgresql
        state: present

    - name: Install packages
      apt:
        name:
         - postgresql
        state: present
      notify:
        - Restart postgresql

    - name: Install python packages
      apt:
        name:
         - python3-psycopg2
        state: present

    - name: Create database
      postgresql_db:
        state: present
        name: zabbix
      become: yes
      become_user: postgres

    - name: Create user postgresql
      become: yes
      become_user: postgres
      postgresql_user:
        name: zabbix
        password: devops
        role_attr_flags: SUPERUSER

    - name: Import schema and data
      ansible.builtin.shell: |
              zcat zcat /usr/share/zabbix-sql-scripts/postgresql/server.sql.gz | sudo -u zabbix psql zabbix

    - name: Update zabbix server configuration
      blockinfile:
        path: /etc/zabbix/zabbix_server.conf
        marker: "# {mark} MANAGED BLOCK"
        block: |
         DBPassword={{ "devops" }}
        state: present

    - name: Change nginx.conf
      lineinfile:
        path: /etc/zabbix/nginx.conf
        regexp: '^(\s*server_name\s+).*'
        line: '        server_name 192.168.20.133;'
        backrefs: yes
        state: present

    - name: Change nginx.conf
      lineinfile:
        path: /etc/zabbix/nginx.conf
        regexp: '^(\s*listen\s+).*'
        line: '        listen 80;'
        backrefs: yes
        state: present

    - name: Restart services
      service:
       name: "{{ item }}"
       state: restarted
      with_items:
        - zabbix-server
        - zabbix-agent2
        - nginx
        - php8.1-fpm

    - name: Enable services
      service:
       name: "{{ item }}"
       state: started
       enabled: yes
      with_items:
        - zabbix-server
        - zabbix-agent2
        - nginx
        - php8.1-fpm

  handlers:
    - name: Restart postgresql
      service:
        name: postgresql
        state: restarted
