---
 - name: Loop test
   hosts: all
   become: yes
   become_method: sudo
   become_user: ch
   tasks:

   - name: Say hello to ALL
     debug: msg="hello {{ item }}"
     loop:
      - "Vasya"
      - "Petya"
      - "Masha"
      - "Olya"

   - name: Loop Until example
     shell: echo -n Z >> myfile.txt && cat myfile.txt
     register: output
     delay: 2
     retries: 10
     until: output.stdout.find("ZZZZ") == false

   - name: Print Final Output
     debug:
       var: output.stdout
